const {url,anonKey}=window.CINE_CONFIG;
const sessionKey='cinelang_teacher_session';
const app=document.querySelector('#app');
const state={session:null,students:[],studentId:'',overview:null,day:dateKey(new Date()),loading:false,error:''};
const cache=new Map();
const cacheTtl=60_000;

function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDate(v){const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function weekStart(d){const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));x.setHours(0,0,0,0);return x}
function isoWeek(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=x.getUTCFullYear(),first=new Date(Date.UTC(y,0,4));first.setUTCDate(first.getUTCDate()+4-(first.getUTCDay()||7));return {year:y,week:1+Math.round((x-first)/604800000)}}
function duration(ms=0){const m=Math.floor(ms/60000);if(m<60)return `${m}分钟`;const h=Math.floor(m/60),r=m%60;return r?`${h}小时${r}分钟`:`${h}小时`}
function review(n){return n<1?'新学习':n===1?'第一次复习':`第${n}次复习`}
function weekday(d){return ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][d.getDay()]}
function icon(type){return ({video:'▣',audio:'♫',emoji:'☺',script:'▤'}[type]||'▱')}
function getCached(k){const item=cache.get(k);return item&&Date.now()-item.at<cacheTtl?item.value:null}
function putCached(k,v){cache.set(k,{at:Date.now(),value:v});return v}
async function api(path,token,body){const res=await fetch(`${url}${path}`,{method:'POST',headers:{apikey:anonKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok)throw new Error(await res.text());return res.json()}
async function refreshSession(saved){const res=await fetch(`${url}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:anonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:saved.refresh_token})});if(!res.ok)throw new Error('expired');return res.json()}
async function login(email,password){const res=await fetch(`${url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:anonKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!res.ok)throw new Error('邮箱或密码不正确，请重新输入。');return res.json()}
async function loadStudents(force=false){const k=`students:${state.session.user?.id||'user'}`;let data=force?null:getCached(k);if(!data)data=putCached(k,await api('/rest/v1/rpc/get_my_students',state.session.access_token,{}));state.students=data;state.studentId=state.studentId||data[0]?.student_id||''}
async function loadOverview(force=false){if(!state.studentId)return;const selected=parseDate(state.day),start=weekStart(selected),from=new Date(start),end=new Date(start),today=new Date();from.setDate(from.getDate()-7);end.setDate(end.getDate()+6);const to=end>today?today:end;const k=`overview:${state.session.user?.id}:${state.studentId}:${dateKey(from)}:${dateKey(to)}`;let data=force?null:getCached(k);if(!data)data=putCached(k,await api('/rest/v1/rpc/get_student_learning_overview',state.session.access_token,{p_student_id:state.studentId,p_from:dateKey(from),p_to:dateKey(to)}));state.overview=data}
async function reload(force=false){state.loading=true;state.error='';render();try{await loadStudents(force);await loadOverview(force)}catch(e){state.error='学习数据暂时无法加载，请检查网络后重试。'}finally{state.loading=false;render()}}
function logout(){localStorage.removeItem(sessionKey);state.session=null;state.overview=null;render()}
function loginView(){return `<main class="login-shell"><form id="login" class="login-card"><small>CineChinese</small><h1>学习陪伴</h1><p>查看学员每天与本周的学习记录</p><label>老师邮箱<input name="email" type="email" autocomplete="email" required></label><label>密码<input name="password" type="password" autocomplete="current-password" required></label><div class="form-error">${state.error}</div><button type="submit">登录</button></form></main>`}
function card(title,trailing,body,cls=''){return `<section class="card ${cls}"><header><h2>${title}</h2>${trailing||''}</header>${body}</section>`}
function dashboard(){if(state.loading&&!state.overview)return `<main class="shell"><div class="state">正在加载学习数据…</div></main>`;if(state.error)return `<main class="shell"><div class="state error">${state.error}<button id="retry">重新加载</button></div></main>`;if(!state.students.length)return `<main class="shell"><div class="state">还没有关联学员</div></main>`;
 const now=new Date(),today=dateKey(now),selected=parseDate(state.day),isToday=state.day===today,learning=state.overview?.days?.find(x=>x.learning_day===state.day),prefix=isToday?'今日':'当日';
 const start=weekStart(selected),days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return {d,data:state.overview?.days?.find(x=>x.learning_day===dateKey(d))}});const total=days.reduce((n,x)=>n+(x.data?.effective_duration_ms||0),0),studied=days.filter(x=>(x.data?.effective_duration_ms||0)>=60000).length,max=Math.max(1,...days.map(x=>x.data?.effective_duration_ms||0)),week=isoWeek(selected),materials=(learning?.materials||[]).filter(x=>x.durationMs>=60000),materialTotal=materials.reduce((n,x)=>n+x.durationMs,0);
 const selector=`<button id="date-trigger" class="date-trigger">${selected.getMonth()+1}月${selected.getDate()}日 · ${weekday(selected)} <span>⌄</span></button>`;
 const metrics=`<div class="metrics"><div><b>${state.overview.unreviewedWordCount}个</b><span>未复习生词</span></div><div><b>${learning?.queried_word_count||0}个</b><span>查询生词</span></div><div><b>${learning?.added_word_count||0}个</b><span>新增生词</span></div></div>`;
 const records=materials.length?`<div class="records">${materials.map(x=>`<div class="record"><span class="material-icon">${icon(x.materialType)}</span><div><b>${escapeHtml(x.materialName)}</b><small>${review(x.reviewCount)}</small></div><time>${duration(x.durationMs)}</time></div>`).join('')}</div>`:`<p class="empty">${isToday?'今天还没有学习记录':'当日没有学习记录'}</p>`;
 const elapsed=isToday?now.getDay()||7:7,previousStart=new Date(start);previousStart.setDate(previousStart.getDate()-7);let previousTotal=0;for(let i=0;i<elapsed;i++){const d=new Date(previousStart);d.setDate(d.getDate()+i);previousTotal+=state.overview?.days?.find(x=>x.learning_day===dateKey(d))?.effective_duration_ms||0}const delta=total-previousTotal,comparison=delta===0?'与上周同期学习时长相同':`比上周同期${delta>0?'多学习':'少学习'} ${duration(Math.abs(delta))}`;
 const bars=`<div class="week-bars">${days.map(x=>{const future=x.d>now,h=future?2:Math.max(2,(x.data?.effective_duration_ms||0)/max*60);return `<button class="bar-slot ${dateKey(x.d)===state.day?'selected':''}" data-day="${dateKey(x.d)}" ${future?'disabled':''} aria-label="${x.d.getMonth()+1}月${x.d.getDate()}日" data-tip="${future?'':duration(x.data?.effective_duration_ms||0)}"><i style="height:${h}px"></i></button>`}).join('')}</div><div class="baseline"></div><div class="weekdays">${['一','二','三','四','五','六','日'].map(x=>`<span>${x}</span>`).join('')}</div>`;
 return `<main class="shell"><section class="student-card"><b>学员选择</b><label><select id="student-select">${state.students.map(x=>`<option value="${x.student_id}" ${x.student_id===state.studentId?'selected':''}>${escapeHtml(x.display_name)}</option>`).join('')}</select><span>⌄</span></label></section>${card(`${prefix}学习`,selector,`<div class="hero"><b>${duration(learning?.effective_duration_ms||0)}</b><span>有效学习</span></div>${metrics}`)}${card(`${prefix}学习记录`,`<b class="trailing">${duration(materialTotal)}</b>`,records)}${card(isToday?'本周学习':'所选周学习',`<span class="period">${week.year}年 · 第${week.week}周</span>`,`<div class="week-total"><b>${duration(total)}</b><span>本周有效学习</span></div><p class="study-days">${studied}天 学习天数</p>${bars}<p class="comparison">${comparison}</p>`,'week-card')}<button id="logout" class="logout">退出登录</button><div id="popover"></div></main>`}
function escapeHtml(v=''){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){app.innerHTML=state.session?dashboard():loginView();bind()}
function bind(){document.querySelector('#login')?.addEventListener('submit',async e=>{e.preventDefault();state.error='';const f=new FormData(e.currentTarget);try{state.session=await login(f.get('email'),f.get('password'));localStorage.setItem(sessionKey,JSON.stringify(state.session));await reload()}catch(err){state.error=err.message;render()}});document.querySelector('#retry')?.addEventListener('click',()=>reload(true));document.querySelector('#logout')?.addEventListener('click',logout);document.querySelector('#student-select')?.addEventListener('change',async e=>{state.studentId=e.target.value;state.overview=null;await reload()});document.querySelector('#date-trigger')?.addEventListener('click',showCalendar);document.querySelectorAll('.bar-slot:not(:disabled)').forEach(el=>el.addEventListener('click',async()=>{state.day=el.dataset.day;state.overview=null;await reload()}))}
function showCalendar(){const trigger=document.querySelector('#date-trigger'),host=document.querySelector('#popover');let picked=parseDate(state.day),shown=new Date(picked.getFullYear(),picked.getMonth(),1);const close=e=>{if(!host.contains(e.target)&&!trigger.contains(e.target)){host.innerHTML='';document.removeEventListener('pointerdown',close)}};function draw(){const first=new Date(shown.getFullYear(),shown.getMonth(),1),offset=(first.getDay()+6)%7,last=new Date(shown.getFullYear(),shown.getMonth()+1,0).getDate(),today=new Date();host.innerHTML=`<section class="calendar"><header><button data-nav="-1">‹</button><b>${shown.getFullYear()}年${shown.getMonth()+1}月</b><button data-nav="1" ${shown.getFullYear()===today.getFullYear()&&shown.getMonth()===today.getMonth()?'disabled':''}>›</button></header><div class="cal-week">${['一','二','三','四','五','六','日'].map(x=>`<span>${x}</span>`).join('')}</div><div class="cal-grid">${'<i></i>'.repeat(offset)}${Array.from({length:last},(_,i)=>{const d=new Date(shown.getFullYear(),shown.getMonth(),i+1),future=d>today,sel=dateKey(d)===dateKey(picked);return `<button data-date="${dateKey(d)}" class="${sel?'selected':''}" ${future?'disabled':''}>${i+1}</button>`}).join('')}</div><footer><button data-cancel>取消</button><button data-confirm>确定</button></footer></section>`;const rect=trigger.getBoundingClientRect(),cal=host.firstElementChild;cal.style.top=`${rect.bottom+2}px`;cal.style.left=`${Math.max(8,Math.min(innerWidth-352,rect.right-344))}px`;host.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{shown=new Date(shown.getFullYear(),shown.getMonth()+Number(x.dataset.nav),1);draw()});host.querySelectorAll('[data-date]').forEach(x=>x.onclick=()=>{picked=parseDate(x.dataset.date);draw()});host.querySelector('[data-cancel]').onclick=()=>host.innerHTML='';host.querySelector('[data-confirm]').onclick=async()=>{state.day=dateKey(picked);state.overview=null;host.innerHTML='';await reload()}}
 draw();setTimeout(()=>document.addEventListener('pointerdown',close),0)}
(async()=>{const raw=localStorage.getItem(sessionKey);if(raw)try{state.session=await refreshSession(JSON.parse(raw));localStorage.setItem(sessionKey,JSON.stringify(state.session));await reload();return}catch{localStorage.removeItem(sessionKey)}render()})();
